[theme]
primaryColor = "#f63366"
backgroundColor = "#ecf1f7"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"


[global]
showWarningOnDirectExecution = true
serverAddress = "streamlit.metriverse.systems"

[ui]
hideTopBar = true
hideSidebarNav = true